# <Version>2025.0416.1616</Version>
name: misc
description: "misc package project"
version: 2025.0416.1616
homepage:

environment:
  sdk: ^3.7.2

dependencies:
  ffi: ^2.1.4
  logger: ^2.5.0
  path: ^1.9.1

dev_dependencies:
  #lints: ^5.1.1
  lints: ^6.0.0
  test: ^1.25.15
