# <Version>2025.0418.0152</Version>
name: misc
description: "misc package project"
version: 2025.0418.0152
homepage:

environment:
  sdk: ^3.7.2

dependencies:
  dynamic_function: ^1.0.1
  ffi: ^2.1.4
  logger: ^2.5.0
  path: ^1.9.1
  sys: ^0.0.1

dev_dependencies:
  lints: ^5.1.1
  #lints: ^6.0.0
  test: ^1.25.15
